INSERT INTO stock (id, product_ref, quantity) VALUES (1, 'SS5', 2500);
INSERT INTO stock (id, product_ref, quantity) VALUES (2, 'SJ5', 678);
INSERT INTO stock (id, product_ref, quantity) VALUES (3, 'SS6', 345);
INSERT INTO stock (id, product_ref, quantity) VALUES (4, 'SN1', 189);
INSERT INTO stock (id, product_ref, quantity) VALUES (5, 'I6', 1000);
INSERT INTO stock (id, product_ref, quantity) VALUES (6, 'I6S', 1500);
INSERT INTO stock (id, product_ref, quantity) VALUES (7, 'I7', 1200);
INSERT INTO stock (id, product_ref, quantity) VALUES (8, 'SS7', 978);
INSERT INTO stock (id, product_ref, quantity) VALUES (9, 'IS5', 620);